<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58234f9c053f9',
	'title' => 'Extended-test',
	'fields' => array (
		array (
			'key' => 'field_58233bd7ecc8f',
			'label' => 'Content Row',
			'name' => 'content_row',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'extended-flex',
				'id' => '',
			),
			'button_label' => 'Add',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '58234f9c0849c',
					'name' => 'column',
					'label' => 'Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5823565cc9934',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => 'test',
								'id' => 'test',
							),
							'button_label' => 'Add Content',
							'min' => '',
							'max' => '',
							'layouts' => array (
								array (
									'key' => '582356e606a74',
									'name' => 'text',
									'label' => 'Text',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58235e5b2665e',
											'label' => 'Text',
											'name' => 'text',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => '',
											'conditional_logic' => '',
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '58235f2551f25',
									'name' => 'image',
									'label' => 'Image',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58235f2b51f26',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '58235f3351f27',
									'name' => 'file',
									'label' => 'File',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58235f3951f28',
											'label' => 'File',
											'name' => 'file',
											'type' => 'post_object',
											'instructions' => '',
											'required' => '',
											'conditional_logic' => '',
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'post_type' => array (
												0 => 'post',
											),
											'taxonomy' => array (
											),
											'allow_null' => 0,
											'multiple' => 0,
											'return_format' => 'object',
											'ui' => 1,
										),
									),
									'min' => '',
									'max' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '58249496fbc2e',
					'name' => 'row',
					'label' => 'Row',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58249496fbc2f',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => 'test',
								'id' => '',
							),
							'button_label' => 'Add Content',
							'min' => '',
							'max' => '',
							'layouts' => array (
								array (
									'key' => '582356e606a74',
									'name' => 'text',
									'label' => 'Text',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58249496fbc30',
											'label' => 'Text',
											'name' => 'text',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '58235f2551f25',
									'name' => 'image',
									'label' => 'Image',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58249496fbc31',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'image',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
											'preview_size' => 'thumbnail',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '58235f3351f27',
									'name' => 'file',
									'label' => 'File',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_58249496fbc32',
											'label' => 'File',
											'name' => 'file',
											'type' => 'post_object',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'post_type' => array (
												0 => 'post',
											),
											'taxonomy' => array (
											),
											'allow_null' => 0,
											'multiple' => 0,
											'return_format' => 'object',
											'ui' => 1,
										),
									),
									'min' => '',
									'max' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-extended.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'author',
		5 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

endif;

?>
